FROM python:3.12-slim
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/app
RUN pip install StaticJinjaPlus==0.1.1
COPY . .
CMD ["python", "main.py", "--srcpath", "MyTemplates", "--outpath", "MyAssembly"]
