FROM ubuntu:20.04
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /usr/src/app
RUN python3 -m venv venv
RUN ./venv/bin/pip install StaticJinjaPlus==0.1.1
COPY . .
CMD ["./venv/bin/python", "main.py", "--srcpath", "MyTemplates", "--outpath", "MyAssembly"]
